### ISSUE TITLE
Error during Evaluation of the model

### ISSUE THREAD

**Issue by RoMartino** [salesforce/CoST#24]
When I run train.py through Electricity.sh script, after training procedure I get this error:
`Traceback (most recent call last):
  File "/content/CoST/train.py", line 110, in <module>
    out, eval_res = tasks.eval_forecasting(model, data, train_slice, valid_slice, test_slice, scaler, pred_lens, n_covariate_cols, args.max_train_length-1)
  File "/content/CoST/tasks/forecasting.py", line 70, in eval_forecasting
    test_pred_inv = scaler.inverse_transform(test_pred)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_data.py", line 1034, in inverse_transform
    X = check_array(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py", line 915, in check_array
    raise ValueError(
ValueError: Found array with dim 4. None expected <= 2.`

**Comment by gorold** [comment]
Please see the FAQs in the README

Q: ValueError: Found array with dim 4. StandardScaler expected <= 2.

A: Please install the appropriate package requirements as found in requirements.txt, in particular, scikit_learn==0.24.1.
